[workspace]
resolver = "3"
members = ["crates/leptos-ui-utils", "crates/leptos-ui-internals"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/mui/base-ui"

[workspace.dependencies]
floating-ui-dom = "0.6.0"
js-sys = "0.3"
reactive_graph = { version = "0.2", default-features = false, features = ["effects"] }
send_wrapper = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = "0.3"
