[package]
name = "leptos-ui"
description = "Leptos component library port of Base UI."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "leptos_ui"
path = "src/lib.rs"

[dependencies]
leptos-ui-utils = { path = "../leptos-ui-utils" }
leptos-ui-internals = { path = "../leptos-ui-internals" }
leptos = { workspace = true, features = ["hydrate"] }
web-sys = { workspace = true }
reactive_graph = { workspace = true }
serde_json = { workspace = true }
send_wrapper = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
leptos = { workspace = true, features = ["csr", "hydration"] }
any_spawner = { version = "0.3", features = ["futures-executor"] }
wasm-bindgen-test = { workspace = true }
serde_json = { workspace = true }
web-sys = { workspace = true, features = [
  "Event",
  "EventInit",
  "KeyboardEvent",
  "KeyboardEventInit",
  "MouseEvent",
  "MouseEventInit",
] }