[package]
name = "base-ui-leptos"
description = "Leptos component library port of Base UI."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "leptos_ui"
path = "src/lib.rs"

[dependencies]
floating-ui-utils = { workspace = true }
base-ui-leptos-utils = { path = "../leptos-ui-utils", version = "0.1.0" }
base-ui-leptos-internals = { path = "../leptos-ui-internals", version = "0.1.0" }
leptos = { workspace = true, features = ["hydrate"] }
web-sys = { workspace = true, features = [
  "ClipboardEvent",
  "DataTransfer",
  "Document",
  "Element",
  "FocusEvent",
  "HtmlElement",
  "HtmlFormElement",
  "HtmlInputElement",
  "KeyboardEvent",
  "Node",
  "PointerEvent",
  "ValidityState",
  "Window",
] }
reactive_graph = { workspace = true }
serde_json = { workspace = true }
send_wrapper = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4"

[dev-dependencies]
leptos = { workspace = true, features = ["csr", "hydration"] }
any_spawner = { version = "0.3", features = ["futures-executor"] }
wasm-bindgen-test = { workspace = true }
serde_json = { workspace = true }
web-sys = { workspace = true, features = [
  "Event",
  "EventInit",
  "KeyboardEvent",
  "KeyboardEventInit",
  "MouseEvent",
  "MouseEventInit",
] }