//! Port of `packages/utils/src/formatErrorMessage.ts` (Base UI Phase A util).
//!
//! Upstream is a two-export pure-string module with no state: a two-argument factory
//! `createFormatErrorMessage(baseUrl, prefix)` returning a formatter, and a default export that
//! is the fixed binding `createFormatErrorMessage('https://base-ui.com/production-error',
//! 'Base UI')` (`packages/utils/src/formatErrorMessage.ts:28-31`). The formatter builds
//! `new URL(baseUrl)`, sets a `code` query parameter, appends one `args[]` parameter per
//! argument in call order (`packages/utils/src/formatErrorMessage.ts:12-14`), and returns the
//! fixed scaffold `${prefix} error #${code}; visit ${url} for the full message.`
//! (`packages/utils/src/formatErrorMessage.ts:15`). The sole source of truth for behavior is
//! `packages/utils/src/formatErrorMessage.test.ts` (49 lines), which pins all five outputs this
//! port is tested against (`specs/utils/formatErrorMessage.md`).
//!
//! Rust adaptations (behavior-preserving where the upstream contract is defined):
//! - The variadic `...args: string[]` tail becomes a `&[&str]` slice parameter; the default
//!   formatter's call shape `formatErrorMessage(code, ...args)` maps to
//!   [`format_error_message`]`(code, args)`.
//! - `code: number` becomes [`i64`]: error codes are integers in every tested and documented
//!   use (the module is consumed by code generated by `@mui/internal-babel-plugin-minify-errors`,
//!   which emits integer literals — `packages/utils/src/formatErrorMessage.ts:19-27`), and JS
//!   `Number#toString` agrees with [`i64::to_string`] across that domain.
//! - Upstream's `new URL(baseUrl)` + `URLSearchParams` mutation is replaced by serializing the
//!   query string directly and appending it to `base_url`. The serializer reproduces
//!   `URLSearchParams`'s `application/x-www-form-urlencoded` byte table exactly (space → `+`,
//!   every byte outside `*-.0-9A-Za-z_` percent-encoded uppercase — hence `args[]` →
//!   `args%5B%5D`), which is the full observable encoding behavior in the tests
//!   (`packages/utils/src/formatErrorMessage.test.ts:41-47`). Base URLs carrying a pre-existing
//!   query string or fragment, and invalid base URLs, are untested upstream
//!   (`specs/utils/formatErrorMessage.md`, "Untested areas"), so the port performs no URL
//!   parsing/validation and always appends the query as if the base URL had none — the tested
//!   domain is reproduced exactly and untested territory is not invented.

/// The upstream default export's base URL binding
/// (`packages/utils/src/formatErrorMessage.ts:29`).
pub const DEFAULT_BASE_URL: &str = "https://base-ui.com/production-error";

/// The upstream default export's prefix binding
/// (`packages/utils/src/formatErrorMessage.ts:30`).
pub const DEFAULT_PREFIX: &str = "Base UI";

/// Serializes a value the way `URLSearchParams` does
/// (`application/x-www-form-urlencoded`): space becomes `+` and every byte outside
/// `*`, `-`, `.`, `0-9`, `A-Z`, `_`, `a-z` becomes uppercase percent-encoded UTF-8
/// (`packages/utils/src/formatErrorMessage.ts:14`, exercised by
/// `packages/utils/src/formatErrorMessage.test.ts:44-46`).
fn form_urlencode(value: &str) -> String {
    let mut encoded = String::with_capacity(value.len());
    for byte in value.as_bytes() {
        match byte {
            b' ' => encoded.push('+'),
            b'*' | b'-' | b'.' | b'0'..=b'9' | b'A'..=b'Z' | b'_' | b'a'..=b'z' => {
                encoded.push(*byte as char)
            }
            _ => {
                encoded.push('%');
                encoded.push_str(&format!("{byte:02X}"));
            }
        }
    }
    encoded
}

/// Serializes the query string the way upstream's `searchParams.set('code', …)` +
/// `searchParams.append('args[]', …)` calls do (`packages/utils/src/formatErrorMessage.ts:13-14`):
/// `code=<code>` first, then one `args%5B%5D=<arg>` pair per argument, in call order, joined
/// with `&` (`packages/utils/src/formatErrorMessage.test.ts:15-17`).
fn serialize_query(code: i64, args: &[&str]) -> String {
    let args_key = form_urlencode("args[]");
    let mut query = format!("code={code}");
    for arg in args {
        query.push('&');
        query.push_str(&args_key);
        query.push('=');
        query.push_str(&form_urlencode(arg));
    }
    query
}

/// Renders one message from the already-bound prefix/base URL, mirroring the upstream
/// formatter body (`packages/utils/src/formatErrorMessage.ts:11-16`).
fn format_message(base_url: &str, prefix: &str, code: i64, args: &[&str]) -> String {
    format!(
        "{prefix} error #{code}; visit {base_url}?{} for the full message.",
        serialize_query(code, args)
    )
}

/// The upstream `createFormatErrorMessage` factory
/// (`packages/utils/src/formatErrorMessage.ts:7-17`): returns a formatter with the same call
/// shape as [`format_error_message`], bound to `base_url` and `prefix`.
pub fn create_format_error_message(
    base_url: impl Into<String>,
    prefix: impl Into<String>,
) -> impl Fn(i64, &[&str]) -> String {
    let base_url = base_url.into();
    let prefix = prefix.into();
    move |code, args| format_message(&base_url, &prefix, code, args)
}

/// The upstream default export (`packages/utils/src/formatErrorMessage.ts:28-31`): the fixed
/// binding of [`create_format_error_message`] to [`DEFAULT_BASE_URL`] and [`DEFAULT_PREFIX`].
///
/// Upstream warns against importing it directly — it is the entry point the code generated by
/// `@mui/internal-babel-plugin-minify-errors` calls, so it must only ever receive string
/// literals whose args are the interpolation values of those literals
/// (`packages/utils/src/formatErrorMessage.ts:19-27`).
pub fn format_error_message(code: i64, args: &[&str]) -> String {
    format_message(DEFAULT_BASE_URL, DEFAULT_PREFIX, code, args)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Mirrors `packages/utils/src/formatErrorMessage.test.ts:6-11`: code only, zero args —
    // the query string is exactly `?code=<code>` with no `args%5B%5D` pairs.
    #[test]
    fn formats_error_message_with_code_only() {
        assert_eq!(
            format_error_message(123, &[]),
            "Base UI error #123; visit https://base-ui.com/production-error?code=123 for the full message."
        );
    }

    // Mirrors `packages/utils/src/formatErrorMessage.test.ts:13-18`: one `args%5B%5D` pair per
    // argument, in argument order, appended after `code`.
    #[test]
    fn formats_error_message_with_code_and_args() {
        assert_eq!(
            format_error_message(456, &["arg1", "arg2"]),
            "Base UI error #456; visit https://base-ui.com/production-error?code=456&args%5B%5D=arg1&args%5B%5D=arg2 for the full message."
        );
    }

    // Mirrors `packages/utils/src/formatErrorMessage.test.ts:22-28`: the scaffold is fixed and
    // only prefix/base URL vary.
    #[test]
    fn creates_a_formatter_with_custom_url_and_prefix() {
        let custom_formatter =
            create_format_error_message("https://example.com/errors", "My Library");
        assert_eq!(
            custom_formatter(789, &[]),
            "My Library error #789; visit https://example.com/errors?code=789 for the full message."
        );
    }

    // Mirrors `packages/utils/src/formatErrorMessage.test.ts:30-39`: a second, independently
    // bound instance behaves identically with args.
    #[test]
    fn creates_a_formatter_that_handles_args_correctly() {
        let custom_formatter =
            create_format_error_message("https://custom.dev/error-page", "Custom UI");
        assert_eq!(
            custom_formatter(100, &["foo", "bar"]),
            "Custom UI error #100; visit https://custom.dev/error-page?code=100&args%5B%5D=foo&args%5B%5D=bar for the full message."
        );
    }

    // Mirrors `packages/utils/src/formatErrorMessage.test.ts:41-47`: special characters in args
    // are encoded, not passed through — space becomes `+` and `&` becomes `%26`.
    #[test]
    fn handles_special_characters_in_args() {
        let custom_formatter = create_format_error_message("https://example.com/errors", "Test");
        assert_eq!(
            custom_formatter(1, &["hello world", "foo&bar"]),
            "Test error #1; visit https://example.com/errors?code=1&args%5B%5D=hello+world&args%5B%5D=foo%26bar for the full message."
        );
    }

    // The serializer's full `application/x-www-form-urlencoded` byte table
    // (`packages/utils/src/formatErrorMessage.ts:12-14`, whose observable behavior the test
    // file pins at `packages/utils/src/formatErrorMessage.test.ts:44-46`): `[]` → `%5B%5D`
    // (the args key itself), space → `+`, `&` → `%26`, `+` → `%2B`, and non-ASCII text as
    // percent-encoded UTF-8.
    #[test]
    fn encodes_query_values_with_the_form_urlencoded_byte_table() {
        assert_eq!(form_urlencode("args[]"), "args%5B%5D");
        assert_eq!(form_urlencode("hello world"), "hello+world");
        assert_eq!(form_urlencode("foo&bar"), "foo%26bar");
        assert_eq!(form_urlencode("a+b"), "a%2Bb");
        assert_eq!(form_urlencode("café"), "caf%C3%A9");
    }

    // The default export is the fixed factory binding with the module's defaults
    // (`packages/utils/src/formatErrorMessage.ts:28-31`); unverified by any upstream test
    // (specs/utils/formatErrorMessage.md) but proven by the original source the spec defers to.
    #[test]
    fn default_formatter_is_the_factory_bound_to_the_defaults() {
        assert_eq!(DEFAULT_BASE_URL, "https://base-ui.com/production-error");
        assert_eq!(DEFAULT_PREFIX, "Base UI");
        assert_eq!(
            format_error_message(456, &["arg1", "arg2"]),
            create_format_error_message(DEFAULT_BASE_URL, DEFAULT_PREFIX)(456, &["arg1", "arg2"])
        );
    }
}
