//! The generated `## API reference` content of the accordion docs page, carried as data.
//!
//! Source: `docs/src/app/(docs)/react/components/accordion/types.md` (24 kB, generated by
//! `pnpm docs:api` from the component's own type definitions), which is what upstream's page renders
//! through `<TypesAccordion.Root />` … `<TypesAccordion.Panel />` (`page.mdx:52-74`). The port has no
//! docs generator, so the generated content is carried here as data — the same approach
//! `crates/docs-app/src/pages/checkbox_page.rs` takes for `<TypesCheckbox.Root />` — and rendered by
//! `crate::reference`, whose element shape and class names are upstream's.
//!
//! Beyond the five parts' `Props` and `Data Attributes` tables, `types.md` also carries the
//! `Additional Types` the page's `<TypesAccordion.* />` components render for themselves
//! (`Accordion.Root.Props`, `Accordion.Root.State`, `Accordion.Root.ChangeEventReason`,
//! `Accordion.Root.ChangeEventDetails`, `Accordion.Root.Value`, and the same set for Item/Header/
//! Trigger/Panel): 15 headings and five `Re-Export of …` lines, carried here as
//! [`crate::reference::AdditionalType`] rows.
//!
//! How this file was produced, so it can be re-derived and audited rather than trusted: every table
//! row, description run (prose / inline code / link), default and anchor was extracted mechanically
//! from `types.md`'s own markdown tables, and the short type label, the rendered (pretty-printed)
//! type form and each panel's slug were read off upstream's live render of
//! `http://127.0.0.1:3005/react/components/accordion` — the page this port mirrors — because the
//! renderer derives those two from the type metadata and `types.md` does not carry them. Nothing here
//! is invented: where `types.md` and the render disagree, the render wins for the two rendered fields
//! and `types.md` for the documented ones.
//!
//! Deliberate deviations, all recorded in `ralph/logs/spec-discrepancies.md` (the same class
//! `crate::reference`'s module docs already record for the prop rows): the type definitions inside
//! the `Additional Types` panels are not carried (their bodies are TypeScript code blocks, the
//! `docs-chrome: code blocks` item's scope), and neither is the panels' `data-shown`/`:target`
//! reveal.

use crate::reference::{self, AdditionalType, DataAttributeRow, ReferenceProp};

// ---- Root ----

/// `types.md:7-11` — the `### Root` summary line (`Groups all parts of the accordion. Renders a `<div>` element.`).
pub(crate) const ROOT_SUMMARY: &[reference::Segment] = &[
    reference::text("Groups all parts of the accordion. Renders a "),
    reference::code("<div>"),
    reference::text(" element."),
];

/// `types.md` — the generated `**Root Props:**` table, in its own order, with each
/// prop's `#AccordionRoot-<name>` anchor as upstream renders it.
pub(crate) const ROOT_PROPS: &[ReferenceProp] = &[
    ReferenceProp {
        name: "defaultValue",
        anchor: "AccordionRoot-defaultValue",
        short_ty: "Value[]",
        ty: "Value[] | undefined",
        default_value: None,
        description: &[
            reference::text(
                "The uncontrolled value of the item(s) that should be initially expanded. To render a controlled accordion, use the ",
            ),
            reference::code("value"),
            reference::text(" prop instead."),
        ],
    },
    ReferenceProp {
        name: "value",
        anchor: "AccordionRoot-value",
        short_ty: "Value[]",
        ty: "Value[] | undefined",
        default_value: None,
        description: &[
            reference::text(
                "The controlled value of the item(s) that should be expanded. To render an uncontrolled accordion, use the ",
            ),
            reference::code("defaultValue"),
            reference::text(" prop instead."),
        ],
    },
    ReferenceProp {
        name: "onValueChange",
        anchor: "AccordionRoot-onValueChange",
        short_ty: "function",
        ty: "| ((\n    value: Value[],\n    eventDetails: Accordion.Root.ChangeEventDetails,\n  ) => void)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "Event handler called when an accordion item is expanded or collapsed.\nProvides the new value as an argument.",
        )],
    },
    ReferenceProp {
        name: "hiddenUntilFound",
        anchor: "AccordionRoot-hiddenUntilFound",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[
            reference::text(
                "Allows the browser's built-in page search to find and expand the panel contents. Overrides the ",
            ),
            reference::code("keepMounted"),
            reference::text(" prop and uses "),
            reference::code("hidden=\"until-found\""),
            reference::text("\nto hide the element without removing it from the DOM."),
        ],
    },
    ReferenceProp {
        name: "loopFocus",
        anchor: "AccordionRoot-loopFocus",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: None,
        description: &[
            reference::text("Deprecated following the "),
            reference::link(
                "https://github.com/w3c/aria-practices/pull/3434",
                "APG guidance update",
            ),
            reference::text(
                "\nto remove roving focus. This prop no longer affects keyboard focus behavior.",
            ),
        ],
    },
    ReferenceProp {
        name: "multiple",
        anchor: "AccordionRoot-multiple",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[reference::text(
            "Whether multiple items can be open at the same time.",
        )],
    },
    ReferenceProp {
        name: "disabled",
        anchor: "AccordionRoot-disabled",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[reference::text(
            "Whether the component should ignore user interaction.",
        )],
    },
    ReferenceProp {
        name: "orientation",
        anchor: "AccordionRoot-orientation",
        short_ty: "Orientation",
        ty: "'horizontal' | 'vertical' | undefined",
        default_value: Some("'vertical'"),
        description: &[
            reference::text("Deprecated following the "),
            reference::link(
                "https://github.com/w3c/aria-practices/pull/3434",
                "APG guidance update",
            ),
            reference::text(
                "\nto remove roving focus. This prop no longer affects keyboard focus behavior.",
            ),
        ],
    },
    ReferenceProp {
        name: "className",
        anchor: "AccordionRoot-className",
        short_ty: "string | function",
        ty: "| string\n| ((\n    state: Accordion.Root.State<Value>,\n  ) => string | undefined)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "CSS class applied to the element, or a function that\nreturns a class based on the component's state.",
        )],
    },
    ReferenceProp {
        name: "style",
        anchor: "AccordionRoot-style",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[reference::text(
            "Style applied to the element, or a function that\nreturns a style object based on the component's state. This port's\naccordion parts do not expose a `style` prop yet.",
        )],
    },
    ReferenceProp {
        name: "keepMounted",
        anchor: "AccordionRoot-keepMounted",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[
            reference::text(
                "Whether to keep the element in the DOM while the panel is closed.\nThis prop is ignored when ",
            ),
            reference::code("hiddenUntilFound"),
            reference::text(" is used."),
        ],
    },
    ReferenceProp {
        name: "render",
        anchor: "AccordionRoot-render",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[
            reference::text(
                "Allows you to replace the component's HTML element\nwith a different tag, or compose it with another component. Accepts a ",
            ),
            reference::code("RenderProp"),
            reference::text("\n or a function that returns the element to render. This port's\naccordion parts do not expose a `render` prop yet."),
        ],
    },
];

/// `types.md` — the generated `**Root Data Attributes:**` table.
pub(crate) const ROOT_DATA_ATTRIBUTES: &[DataAttributeRow] = &[
    DataAttributeRow {
        name: "data-orientation",
        description: &[reference::text(
            "Indicates the orientation of the accordion.",
        )],
    },
    DataAttributeRow {
        name: "data-disabled",
        description: &[reference::text("Present when the accordion is disabled.")],
    },
];

/// Upstream's `AdditionalTypes` panels for this part
pub(crate) const ROOT_ADDITIONAL_TYPES: &[AdditionalType] = &[
    AdditionalType {
        name: "Accordion.Root.Props",
        slug: "root.props",
        re_export_of: Some(("Root", "AccordionRootProps")),
    },
    AdditionalType {
        name: "Accordion.Root.State",
        slug: "root.state",
        re_export_of: None,
    },
    AdditionalType {
        name: "Accordion.Root.ChangeEventReason",
        slug: "root.changeeventreason",
        re_export_of: None,
    },
    AdditionalType {
        name: "Accordion.Root.ChangeEventDetails",
        slug: "root.changeeventdetails",
        re_export_of: None,
    },
    AdditionalType {
        name: "Accordion.Root.Value",
        slug: "root.value",
        re_export_of: None,
    },
];

// ---- Item ----

/// `types.md:151-155` — the `### Item` summary line (`Groups an accordion header with the corresponding panel. Renders a `<div>` element.`).
pub(crate) const ITEM_SUMMARY: &[reference::Segment] = &[
    reference::text("Groups an accordion header with the corresponding panel. Renders a "),
    reference::code("<div>"),
    reference::text(" element."),
];

/// `types.md` — the generated `**Item Props:**` table, in its own order, with each
/// prop's `#AccordionItem-<name>` anchor as upstream renders it.
pub(crate) const ITEM_PROPS: &[ReferenceProp] = &[
    ReferenceProp {
        name: "value",
        anchor: "AccordionItem-value",
        short_ty: "any",
        ty: "any | undefined",
        default_value: None,
        description: &[reference::text(
            "A unique value that identifies this accordion item.\nIf no value is provided, a unique ID will be generated automatically.\nUse when controlling the accordion programmatically, or to set an initial\nopen state.",
        )],
    },
    ReferenceProp {
        name: "onOpenChange",
        anchor: "AccordionItem-onOpenChange",
        short_ty: "function",
        ty: "| ((\n    open: boolean,\n    eventDetails: Accordion.Item.ChangeEventDetails,\n  ) => void)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "Event handler called when the panel is opened or closed.",
        )],
    },
    ReferenceProp {
        name: "disabled",
        anchor: "AccordionItem-disabled",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[reference::text(
            "Whether the component should ignore user interaction.",
        )],
    },
    ReferenceProp {
        name: "className",
        anchor: "AccordionItem-className",
        short_ty: "string | function",
        ty: "| string\n| ((state: Accordion.Item.State) => string | undefined)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "CSS class applied to the element, or a function that\nreturns a class based on the component's state.",
        )],
    },
    ReferenceProp {
        name: "style",
        anchor: "AccordionItem-style",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[reference::text(
            "Style applied to the element, or a function that\nreturns a style object based on the component's state. This port's\naccordion parts do not expose a `style` prop yet.",
        )],
    },
    ReferenceProp {
        name: "render",
        anchor: "AccordionItem-render",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[
            reference::text(
                "Allows you to replace the component's HTML element\nwith a different tag, or compose it with another component. Accepts a ",
            ),
            reference::code("RenderProp"),
            reference::text("\n or a function that returns the element to render. This port's\naccordion parts do not expose a `render` prop yet."),
        ],
    },
];

/// `types.md` — the generated `**Item Data Attributes:**` table.
pub(crate) const ITEM_DATA_ATTRIBUTES: &[DataAttributeRow] = &[
    DataAttributeRow {
        name: "data-open",
        description: &[reference::text("Present when the accordion item is open.")],
    },
    DataAttributeRow {
        name: "data-disabled",
        description: &[reference::text(
            "Present when the accordion item is disabled.",
        )],
    },
    DataAttributeRow {
        name: "data-index",
        description: &[reference::text(
            "Indicates the index of the accordion item.",
        )],
    },
];

/// Upstream's `AdditionalTypes` panels for this part
pub(crate) const ITEM_ADDITIONAL_TYPES: &[AdditionalType] = &[
    AdditionalType {
        name: "Accordion.Item.Props",
        slug: "item.props",
        re_export_of: Some(("Item", "AccordionItemProps")),
    },
    AdditionalType {
        name: "Accordion.Item.State",
        slug: "item.state",
        re_export_of: None,
    },
    AdditionalType {
        name: "Accordion.Item.ChangeEventReason",
        slug: "item.changeeventreason",
        re_export_of: None,
    },
    AdditionalType {
        name: "Accordion.Item.ChangeEventDetails",
        slug: "item.changeeventdetails",
        re_export_of: None,
    },
];

// ---- Header ----

/// `types.md:244-248` — the `### Header` summary line (`A heading that labels the corresponding panel. Renders an `<h3>` element.`).
pub(crate) const HEADER_SUMMARY: &[reference::Segment] = &[
    reference::text("A heading that labels the corresponding panel. Renders an "),
    reference::code("<h3>"),
    reference::text(" element."),
];

/// `types.md` — the generated `**Header Props:**` table, in its own order, with each
/// prop's `#AccordionHeader-<name>` anchor as upstream renders it.
pub(crate) const HEADER_PROPS: &[ReferenceProp] = &[
    ReferenceProp {
        name: "className",
        anchor: "AccordionHeader-className",
        short_ty: "string | function",
        ty: "| string\n| ((state: Accordion.Header.State) => string | undefined)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "CSS class applied to the element, or a function that\nreturns a class based on the component's state.",
        )],
    },
    ReferenceProp {
        name: "style",
        anchor: "AccordionHeader-style",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[reference::text(
            "Style applied to the element, or a function that\nreturns a style object based on the component's state. This port's\naccordion parts do not expose a `style` prop yet.",
        )],
    },
    ReferenceProp {
        name: "render",
        anchor: "AccordionHeader-render",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[
            reference::text(
                "Allows you to replace the component's HTML element\nwith a different tag, or compose it with another component. Accepts a ",
            ),
            reference::code("RenderProp"),
            reference::text("\n or a function that returns the element to render. This port's\naccordion parts do not expose a `render` prop yet."),
        ],
    },
];

/// `types.md` — the generated `**Header Data Attributes:**` table.
pub(crate) const HEADER_DATA_ATTRIBUTES: &[DataAttributeRow] = &[
    DataAttributeRow {
        name: "data-open",
        description: &[reference::text("Present when the accordion item is open.")],
    },
    DataAttributeRow {
        name: "data-disabled",
        description: &[reference::text(
            "Present when the accordion item is disabled.",
        )],
    },
    DataAttributeRow {
        name: "data-index",
        description: &[reference::text(
            "Indicates the index of the accordion item.",
        )],
    },
];

/// Upstream's `AdditionalTypes` panels for this part
pub(crate) const HEADER_ADDITIONAL_TYPES: &[AdditionalType] = &[
    AdditionalType {
        name: "Accordion.Header.Props",
        slug: "header.props",
        re_export_of: Some(("Header", "AccordionHeaderProps")),
    },
    AdditionalType {
        name: "Accordion.Header.State",
        slug: "header.state",
        re_export_of: None,
    },
];

// ---- Trigger ----

/// `types.md:96-100` — the `### Trigger` summary line (`A button that opens and closes the corresponding panel. Renders a `<button>` element.`).
pub(crate) const TRIGGER_SUMMARY: &[reference::Segment] = &[
    reference::text("A button that opens and closes the corresponding panel. Renders a "),
    reference::code("<button>"),
    reference::text(" element."),
];

/// `types.md` — the generated `**Trigger Props:**` table, in its own order, with each
/// prop's `#AccordionTrigger-<name>` anchor as upstream renders it.
pub(crate) const TRIGGER_PROPS: &[ReferenceProp] = &[
    ReferenceProp {
        name: "nativeButton",
        anchor: "AccordionTrigger-nativeButton",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("true"),
        description: &[
            reference::text("Whether the component renders a native "),
            reference::code("<button>"),
            reference::text(" element when replacing it\nvia the "),
            reference::code("render"),
            reference::text(" prop.\nSet to "),
            reference::code("false"),
            reference::text(" if the rendered element is not a button (for example, "),
            reference::code("<div>"),
            reference::text(")."),
        ],
    },
    ReferenceProp {
        name: "className",
        anchor: "AccordionTrigger-className",
        short_ty: "string | function",
        ty: "| string\n| ((state: Accordion.Trigger.State) => string | undefined)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "CSS class applied to the element, or a function that\nreturns a class based on the component's state.",
        )],
    },
    ReferenceProp {
        name: "style",
        anchor: "AccordionTrigger-style",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[reference::text(
            "Style applied to the element, or a function that\nreturns a style object based on the component's state. This port's\naccordion parts do not expose a `style` prop yet.",
        )],
    },
    ReferenceProp {
        name: "render",
        anchor: "AccordionTrigger-render",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[
            reference::text(
                "Allows you to replace the component's HTML element\nwith a different tag, or compose it with another component. Accepts a ",
            ),
            reference::code("RenderProp"),
            reference::text("\n or a function that returns the element to render. This port's\naccordion parts do not expose a `render` prop yet."),
        ],
    },
];

/// `types.md` — the generated `**Trigger Data Attributes:**` table.
pub(crate) const TRIGGER_DATA_ATTRIBUTES: &[DataAttributeRow] = &[
    DataAttributeRow {
        name: "data-panel-open",
        description: &[reference::text("Present when the accordion panel is open.")],
    },
    DataAttributeRow {
        name: "data-disabled",
        description: &[reference::text(
            "Present when the accordion item is disabled.",
        )],
    },
];

/// Upstream's `AdditionalTypes` panels for this part
pub(crate) const TRIGGER_ADDITIONAL_TYPES: &[AdditionalType] = &[
    AdditionalType {
        name: "Accordion.Trigger.Props",
        slug: "trigger.props",
        re_export_of: Some(("Trigger", "AccordionTriggerProps")),
    },
    AdditionalType {
        name: "Accordion.Trigger.State",
        slug: "trigger.state",
        re_export_of: None,
    },
];

// ---- Panel ----

/// `types.md:299-303` — the `### Panel` summary line (`A collapsible panel with the accordion item contents. Renders a `<div>` element.`).
pub(crate) const PANEL_SUMMARY: &[reference::Segment] = &[
    reference::text("A collapsible panel with the accordion item contents. Renders a "),
    reference::code("<div>"),
    reference::text(" element."),
];

/// `types.md` — the generated `**Panel Props:**` table, in its own order, with each
/// prop's `#AccordionPanel-<name>` anchor as upstream renders it.
pub(crate) const PANEL_PROPS: &[ReferenceProp] = &[
    ReferenceProp {
        name: "hiddenUntilFound",
        anchor: "AccordionPanel-hiddenUntilFound",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[
            reference::text(
                "Allows the browser's built-in page search to find and expand the panel contents. Overrides the ",
            ),
            reference::code("keepMounted"),
            reference::text(" prop and uses "),
            reference::code("hidden=\"until-found\""),
            reference::text("\nto hide the element without removing it from the DOM."),
        ],
    },
    ReferenceProp {
        name: "className",
        anchor: "AccordionPanel-className",
        short_ty: "string | function",
        ty: "| string\n| ((state: Accordion.Panel.State) => string | undefined)\n| undefined",
        default_value: None,
        description: &[reference::text(
            "CSS class applied to the element, or a function that\nreturns a class based on the component's state.",
        )],
    },
    ReferenceProp {
        name: "style",
        anchor: "AccordionPanel-style",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[reference::text(
            "Style applied to the element, or a function that\nreturns a style object based on the component's state. This port's\naccordion parts do not expose a `style` prop yet.",
        )],
    },
    ReferenceProp {
        name: "keepMounted",
        anchor: "AccordionPanel-keepMounted",
        short_ty: "boolean",
        ty: "boolean | undefined",
        default_value: Some("false"),
        description: &[
            reference::text(
                "Whether to keep the element in the DOM while the panel is closed.\nThis prop is ignored when ",
            ),
            reference::code("hiddenUntilFound"),
            reference::text(" is used."),
        ],
    },
    ReferenceProp {
        name: "render",
        anchor: "AccordionPanel-render",
        short_ty: "not exposed",
        ty: "not exposed by this port yet",
        default_value: None,
        description: &[
            reference::text(
                "Allows you to replace the component's HTML element\nwith a different tag, or compose it with another component. Accepts a ",
            ),
            reference::code("RenderProp"),
            reference::text("\n or a function that returns the element to render. This port's\naccordion parts do not expose a `render` prop yet."),
        ],
    },
];

/// `types.md` — the generated `**Panel Data Attributes:**` table.
pub(crate) const PANEL_DATA_ATTRIBUTES: &[DataAttributeRow] = &[
    DataAttributeRow {
        name: "data-open",
        description: &[reference::text("Present when the accordion panel is open.")],
    },
    DataAttributeRow {
        name: "data-orientation",
        description: &[reference::text(
            "Indicates the orientation of the accordion.",
        )],
    },
    DataAttributeRow {
        name: "data-disabled",
        description: &[reference::text(
            "Present when the accordion item is disabled.",
        )],
    },
    DataAttributeRow {
        name: "data-index",
        description: &[reference::text(
            "Indicates the index of the accordion item.",
        )],
    },
    DataAttributeRow {
        name: "data-starting-style",
        description: &[reference::text(
            "Present when the panel begins animating in.",
        )],
    },
    DataAttributeRow {
        name: "data-ending-style",
        description: &[reference::text("Present when the panel is animating out.")],
    },
];

/// `types.md` — the generated `**Panel CSS Variables:**` table.
pub(crate) const PANEL_CSS_VARIABLES: &[DataAttributeRow] = &[
    DataAttributeRow {
        name: "--accordion-panel-height",
        description: &[reference::text("The accordion panel's height.")],
    },
    DataAttributeRow {
        name: "--accordion-panel-width",
        description: &[reference::text("The accordion panel's width.")],
    },
];

/// Upstream's `AdditionalTypes` panels for this part
pub(crate) const PANEL_ADDITIONAL_TYPES: &[AdditionalType] = &[
    AdditionalType {
        name: "Accordion.Panel.Props",
        slug: "panel.props",
        re_export_of: Some(("Panel", "AccordionPanelProps")),
    },
    AdditionalType {
        name: "Accordion.Panel.State",
        slug: "panel.state",
        re_export_of: None,
    },
];
