#!/usr/bin/env bash
# scorecard-sweep.sh — measure a few routes per invocation and keep one aggregate page scorecard.
#
# WHY ROTATION AND NOT "ALL 18 AT ONCE": each route costs several browser runs (structure, parity, snippets,
# copy, mentions) and this box shares a 512-task cgroup with the loop, cargo and the gateway. A full sweep in
# one go would either starve the loop or be killed by it. So each invocation measures the next N routes
# (default 3), wrapping around, and the aggregate is always the union of the latest measurement per route.
# Scheduled hourly, a full pass covers all mirrored routes every few hours.
#
# It also respects the box: above the task ceiling it declines to run rather than becoming the starver (which
# is how a sweep once killed the watchdog cron with Errno 11), and it never claims a verdict for a route it
# did not measure — a route missing from the aggregate is reported as UNMEASURED, not as passing.
#
# Usage: scorecard-sweep.sh [routes_per_run]
set -uo pipefail
cd /data/workspace/baseui

LIMIT="${1:-3}"
STATE="ralph/generated/scorecard-state.json"
JSONL="ralph/generated/scorecard.jsonl"
LOG="ralph/logs/scorecard-sweep.log"
mkdir -p ralph/generated ralph/logs/scorecard

PIDS_CURRENT=$(cat /sys/fs/cgroup/pids.current 2>/dev/null || echo 0)
PIDS_MAX=$(cat /sys/fs/cgroup/pids.max 2>/dev/null || echo 512)
if [ "$PIDS_CURRENT" -gt $((PIDS_MAX - 90)) ]; then
  echo "$(date -u +%FT%TZ) skip: box under pressure ($PIDS_CURRENT/$PIDS_MAX tasks)" >> "$LOG"
  exit 0
fi

# Keep the local docs server alive: every axis here measures the port's real render.
if ! curl -s -o /dev/null --max-time 8 http://127.0.0.1:3177/; then
  (python3 ralph/scripts/serve-docs-app.py --port 3177 >/dev/null 2>&1 &) 
  sleep 6
fi

ROUTES="$(python3 - <<'PY'
import json
try:
    d = json.load(open('ralph/generated/visual-baseline.json'))
    routes = sorted(d.get('routes', {}).keys())
except Exception:
    routes = []
print('\n'.join(routes))
PY
)"
[ -z "$ROUTES" ] && { echo "$(date -u +%FT%TZ) skip: no routes recorded yet" >> "$LOG"; exit 0; }
TOTAL=$(printf '%s\n' "$ROUTES" | wc -l | tr -d ' ')

NEXT=0
[ -f "$STATE" ] && NEXT=$(python3 -c "import json;print(json.load(open('$STATE')).get('nextIndex',0))" 2>/dev/null || echo 0)

measured=0
for i in $(seq 0 $((LIMIT - 1))); do
  IDX=$(( (NEXT + i) % TOTAL ))
  ROUTE=$(printf '%s\n' "$ROUTES" | sed -n "$((IDX + 1))p")
  [ -z "$ROUTE" ] && continue
  NAME="${ROUTE##*/}"
  OUT="$(timeout 420 node ralph/scripts/check-page.mjs --route "$ROUTE" --json 2>/dev/null || true)"
  if printf '%s' "$OUT" | grep -q '"verdict"'; then
    # Keep only the JSON object: robust even if a future check-page emits a trailing human line.
    printf '%s' "$OUT" | python3 -c "import sys,json;raw=sys.stdin.read();i=raw.find('{');j=raw.rfind('}');print(json.dumps(json.loads(raw[i:j+1])) if i>=0 and j>i else '')" >> "$JSONL" 
    measured=$((measured + 1))
  else
    echo "$(date -u +%FT%TZ) $ROUTE unmeasured (no verdict produced)" >> "$LOG"
  fi
done

python3 - "$(( (NEXT + LIMIT) % TOTAL ))" <<'PY' >> "$LOG"
import json, sys, collections
next_index = int(sys.argv[1])
json.dump({"nextIndex": next_index, "updatedAt": __import__('datetime').datetime.utcnow().isoformat()+"Z"},
          open('ralph/generated/scorecard-state.json','w'))

latest = {}
for line in open('ralph/generated/scorecard.jsonl'):
    line = line.strip()
    if not line: continue
    try: d = json.loads(line)
    except Exception: continue
    latest[d.get('route')] = d          # last measurement wins

rows = sorted(latest.values(), key=lambda d: d.get('route',''))
passing = [d for d in rows if d.get('verdict') == 'PASS']
axis_fail = collections.Counter()
for d in rows:
    for a in d.get('axes', []):
        if a.get('status') != 'PASS': axis_fail[a.get('axis')] += 1

lines = ["# Page scorecard — aggregate", "",
         f"Measured {len(rows)} of 18 mirrored routes; **{len(passing)} pass every axis**. Generated by `ralph/scripts/scorecard-sweep.sh` (rotating; last update {__import__('datetime').datetime.now(__import__('datetime').timezone.utc).isoformat()}).",
         "", "An unmeasured axis never counts as a pass.", ""]
for d in rows:
    bad = [a['axis'] for a in d.get('axes', []) if a.get('status') != 'PASS']
    lines.append(f"- **{d.get('verdict')}** `{d.get('route')}`" + (f" — failing: {', '.join(bad)}" if bad else ""))
lines += ["", "## Failing axes across measured routes", ""]
for axis, n in axis_fail.most_common():
    lines.append(f"- {axis}: {n} route(s)")
open('ralph/logs/scorecard.md','w').write('\n'.join(lines) + '\n')

measured_routes = {d.get('route') for d in rows}
missing = [r for r in json.load(open('ralph/generated/visual-baseline.json')).get('routes', {}) if r not in measured_routes]
print(f"aggregate: {len(passing)}/{len(rows)} routes pass all axes; {len(missing)} not yet measured")
print("digest-axes: " + ", ".join(f"{a}={n}" for a, n in axis_fail.most_common(4)))
PY

echo "$(date -u +%FT%TZ) sweep: measured $measured route(s) of $TOTAL" >> "$LOG"
# One-line digest for the chat: routes passing the scorecard, out of those measured.
if [ "$measured" -gt 0 ]; then
  PASS_LINE=$(grep -m1 'Measured ' ralph/logs/scorecard.md 2>/dev/null)
  echo "scorecard sweep: ${PASS_LINE#Measured }"
fi
